version: '3'

services:
  db:
    container_name: goal_db
    image: postgres:14
    environment:
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_NAME}'
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - goal_backend_pgdata:/var/lib/postgresql/data
    restart: unless-stopped
  mysql-db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'

volumes:
  goal_backend_pgdata:
